# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 20:43
from __future__ import unicode_literals

import dam.models
from django.conf import settings
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Enable Postgres hstore - need to be Postgres superuser
        # Comment line below out on local instance as needed and
        # set from psql console instead
        HStoreExtension(),
        # Auto-generated migration follows
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.ImageField(height_field='height', max_length=36, upload_to=dam.models._gen_image_filename, width_field='width')),
                ('format', models.CharField(max_length=8)),
                ('proxy_data', models.ImageField(blank=True, max_length=36, null=True, upload_to=dam.models._gen_thumbs_filename)),
                ('original_filename', models.TextField()),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('exif_tags', django.contrib.postgres.fields.hstore.HStoreField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
