# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 21:48
from __future__ import unicode_literals

import dam.models
import dam.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_data',
            field=models.ImageField(height_field='height', max_length=64, upload_to=dam.models._gen_image_filename, validators=[dam.validators.file_size], width_field='width'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='proxy_data',
            field=models.ImageField(blank=True, max_length=64, null=True, upload_to=dam.models._gen_thumbs_filename),
        ),
    ]
