# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dam', '0004_auto_20170504_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(max_length=64),
        ),
    ]
