# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dam', '0005_auto_20170504_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=127),
        ),
    ]
