# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 22:42
from __future__ import unicode_literals

import dam.models
import dam.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dam', '0007_auto_20170505_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='height',
            new_name='image_height',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='width',
            new_name='image_width',
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_data',
            field=models.ImageField(height_field='image_height', upload_to=dam.models._gen_image_filename, validators=[dam.validators.file_size], width_field='image_width'),
        ),
    ]
