# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 00:57
from __future__ import unicode_literals

import dam.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dam', '0008_auto_20170505_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='proxy_data',
            field=models.ImageField(blank=True, height_field='proxy_height', null=True, upload_to=dam.models._gen_thumbs_filename, width_field='proxy_width'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='proxy_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='proxy_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
