# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 21:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dam', '0010_auto_20170506_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExifTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(blank=True, max_length=128)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('_f_number', django.contrib.postgres.fields.hstore.HStoreField(blank=True)),
                ('_focal_length', django.contrib.postgres.fields.hstore.HStoreField(blank=True)),
                ('_exposure_time', django.contrib.postgres.fields.hstore.HStoreField(blank=True)),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exif', to='dam.Photo')),
            ],
        ),
    ]
